# Generated by Django 2.2.4 on 2019-08-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlist', '0003_ulist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulist',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
