# Generated by Django 2.2.4 on 2019-08-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlist', '0004_auto_20190831_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulist',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
