# Generated by Django 2.2.4 on 2019-08-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlist', '0005_auto_20190831_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulist',
            name='visit_num',
        ),
    ]
